name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ main ]


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      id: 1
      run: pytest
    - name: timetest
      id: 2
      run: python timetest.py
    - name: send_message
      uses: appleboy/telegram-action@master
          with:
            to: '-1001740631878'
            token: '5010718556:AAH-9hYZW2txZyUh4p2n1Yf-b__4HVj0Sto'
            message: |
              Repository: ${{ github.repository }}
              pytest results: ${{ steps.1.outcome }} 
              timetest results: ${{ steps.2.outcome }}   

              See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
